[project]
name = "jellyfetch"
version = "0.1.1"
description = "A feature-rich command-line media downloader and web dashboard"
readme = "README.md"
dependencies = ["yt-dlp", "flask", "python-dotenv", "yt-dlp-ejs"]

[project.scripts]
download = "jellyfetch.fetcher:main"

[tool.setuptools]
packages = ["jellyfetch"]